/* 
 * PED Test API
 *
 * PED Test API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReasonCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReasonCodeTests
    {
        // TODO uncomment below to declare an instance variable for ReasonCode
        //private ReasonCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReasonCode
            //instance = new ReasonCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReasonCode
        /// </summary>
        [Test]
        public void ReasonCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReasonCode
            //Assert.IsInstanceOfType<ReasonCode> (instance, "variable 'instance' is a ReasonCode");
        }


        /// <summary>
        /// Test the property 'ReasonCodeId'
        /// </summary>
        [Test]
        public void ReasonCodeIdTest()
        {
            // TODO unit test for the property 'ReasonCodeId'
        }
        /// <summary>
        /// Test the property 'ReasonCodeName'
        /// </summary>
        [Test]
        public void ReasonCodeNameTest()
        {
            // TODO unit test for the property 'ReasonCodeName'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

    }

}
