/* 
 * PED Test API
 *
 * PED Test API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing States
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatesTests
    {
        // TODO uncomment below to declare an instance variable for States
        //private States instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of States
            //instance = new States();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of States
        /// </summary>
        [Test]
        public void StatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" States
            //Assert.IsInstanceOfType<States> (instance, "variable 'instance' is a States");
        }


        /// <summary>
        /// Test the property 'StateId'
        /// </summary>
        [Test]
        public void StateIdTest()
        {
            // TODO unit test for the property 'StateId'
        }
        /// <summary>
        /// Test the property 'StateName'
        /// </summary>
        [Test]
        public void StateNameTest()
        {
            // TODO unit test for the property 'StateName'
        }
        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Test]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }

    }

}
