/* 
 * PED Test API
 *
 * PED Test API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AdminApiTests
    {
        private AdminApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AdminApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdminApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AdminApi
            //Assert.IsInstanceOfType(typeof(AdminApi), instance, "instance is a AdminApi");
        }

        /// <summary>
        /// Test AddInventory
        /// </summary>
        [Test]
        public void AddInventoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InventoryItem body = null;
            //instance.AddInventory(body);
            
        }
        /// <summary>
        /// Test SearchInventory
        /// </summary>
        [Test]
        public void SearchInventoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchString = null;
            //int? skip = null;
            //int? limit = null;
            //var response = instance.SearchInventory(searchString, skip, limit);
            //Assert.IsInstanceOf<List<InventoryItem>> (response, "response is List<InventoryItem>");
        }
    }

}
