/* 
 * PED Test API
 *
 * PED Test API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SharedApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SharedApiTests
    {
        private SharedApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SharedApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SharedApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SharedApi
            //Assert.IsInstanceOfType(typeof(SharedApi), instance, "instance is a SharedApi");
        }

        /// <summary>
        /// Test ReasonCodes
        /// </summary>
        [Test]
        public void ReasonCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ReasonCodes();
            //Assert.IsInstanceOf<List<ReasonCode>> (response, "response is List<ReasonCode>");
        }
        /// <summary>
        /// Test States
        /// </summary>
        [Test]
        public void StatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.States();
            //Assert.IsInstanceOf<List<State>> (response, "response is List<State>");
        }
    }

}
